sites = {
    'A Clean PortoCo': ['Eagle Pass, TX', 'Laredo, TX', 'Harlingen, TX', 'San Antonio, TX'],
    'A John': ['Poughkeepsie, NY'],
    'A Sani Can': ['Charlotte, NC', 'Greensboro, NC'],
    'A1 Porta Potty': ['New Albany, IN'],
    'Arkansas Portable Toilets': ['Little Rock, AR', 'Fayetteville, AR'],
    'Blue Moon Restrooms': ['Lexington, KY'],
    "Bucky's Restrooms": ['Madison, WI'],
    'Bullitt Septic Service': ['Shepherdsville, KY'],
    'C&L': ['Toledo, OH'],
    'Cesspool Cleaners': ['Eau Claire, WI'],
    'Colorado Portables': ['Denver, CO'],
    'East Tennessee Portables': ['Knoxville, TN', 'Cookeville, TN'],
    'Event Solutions': ['Lafayette, LA', 'Lake Charles, LA', 'Beaumont, TX', 'Leesville, LA', 'Pecos, LA'],
    'Forza': ['Lubbock, TX', 'Kermit, TX', 'Pecos, TX', 'Goldthwaite, TX', 'Seminole, TX', 'Las Cruces, NM', 'San Angelo, TX'],
    'Freedom Waste': ['Port St. Lucie, FL', 'Miami, FL'],
    'FusionSite Iowa': ['Cedar Rapids, IA'],
    'FusionSite Mississippi': ['Oxford, MS'],
    'FusionSite Nashville': ['Nashville, TN'],
    'Georgia Containers': ['Atlanta, GA'],
    'Gotta Go': ['Jackson, MS'],
    'Griffin Waste': ['Asheville, NC', 'Brevard, NC'],
    'J Bar': ['Austin, TX', 'San Marcos, TX'],
    'Little John': ['Greenville, SC'],
    'MC Septic': ['Johnson City, TN'],
    'Maxwell Septic': ['Gallatin, TN', 'Bowling Green, KY', 'Nashville, TN'],
    'Moon Companies': ['Louisville, KY'],
    'Pacific Portables': ['Los Angeles, CA'],
    'Port A Bowl': ['Philadelphia, PA', 'Allentown, PA'],
    'Porta Serve': ['Gainesville, FL'],
    'Portable Services': ['Augusta, GA', 'Columbia, SC'],
    'R & R': ['Wytheville, VA'],
    'Rent A Can': ['Phoenix, AZ', 'Casa Grande, AZ'],
    'Rent A John': ['Columbus, OH'],
    'Safety Quip': ['Memphis, TN'],
    'Sarabias': ['El Paso, TX'],
    'Southwest Florida': ['Naples, FL', 'Fort Myers, FL'],
    'Stamback': ['Tucson, AZ'],
    'Stranders Sanitary': ['Lodi, WI'],
    'The Bolles Company': ['Chattanooga, TN'],
    'Versatile Industries': ['Midland, TX', 'Dallas, TX'],
}

# stores export tab - Marketing footprint
